config/routes.rb
Rails.application.routes.draw do

  
  
  resources :comments
  resources :categories
  resources :posts
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get '/edit' => 'users#edit'
  get '/signup'  => 'users#new'
  get '/reset_password'  => 'forgot_password#update'
  get '/forgot_password'  => 'forgot_password#new'
  match '/forgot_password' => 'forgot_password#send_email', via: :post
  match '/login', to: 'sessions#create', via: :post
  match '/login', to: 'sessions#new', via: :get
  get '/auth/:provider/callback', :to => 'sessions#create_omniauth'
  get '/auth/failure', :to => 'sessions#failure'
  get '/showprofile' => 'users#show'
 
  
  
  match '/users/validate/:id/:email_confirm_string', to: 'users#validate_from_email', via: :get
  match '/users/pwr/:id/:email_confirm_string', to: 'forgot_password#reset_password', via: :get
  match '/forgot_password.:id', to: 'forgot_password#update', via: :patch
  get '/flagpost', to: 'posts#flagpost'

  get '/logout', :to => 'sessions#destroy'

  get '/login2', :to => 'sessions#create'
  root :to => "posts#index"
  
  get '/search', :to => 'posts#search'

  get '/cast_vote', to: 'votes#cast_vote'
  
   resources :relationships,       only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :votes
  has_many :comments
  has_many :relateds, foreign_key: :post_id1
  has_many :related_posts, through: :relateds, source: :related_post2
  belongs_to :user

  before_save :before_save

  def before_save
    score = overall_votes
    sign = score <=> 0
    order = Math.log10([score.abs, 1].max)
    created_at = self.created_at.nil? ? Time.now : self.created_at
    time = created_at.to_f - 1134028003
    self.trending = (order * sign + time / 45000).round(7)
  end

  def overall_votes
    upvotes = votes.where(updown_cd: 0).count
    downvotes = votes.where(updown_cd: 1).count
    return upvotes - downvotes
  end

  def is_voted_by_user(current_user, updown)
    if current_user.nil?
      return false
    end
    return votes.where(updown_cd: updown, user_id: current_user.id).count == 1
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('trending DESC').where(params.permit(:category_id))
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_title = @post.title
    @comment = Comment.new()
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @current_user == nil || @current_user.id != @post.user_id
      redirect_to post_path id:@post.id
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    if @current_user != nil
      @post = Post.new(post_params)
      #Can also look into the build method
      @post.user_id = @current_user.id
  
      if @post.save
        flash[:notice] = 'Post was successfully created.'
        redirect_to @post
      else
        render :new
      end
    else
      flash[:notice] = 'Login to create a new post.'
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @current_user != nil && @current_user.id == @post.user_id
      respond_to do |format|
        #might have to add user ID
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @current_user != nil && @current_user.id == @post.user_id
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Must be your post inorder to destroy it.' }
        format.json { head :no_content }
      end
    end
  end
  
  def search
    if params[:search_terms] != "" && params[:search_terms] != nil
      @posts = Array.new()
      Post.order('trending DESC').all.each do |pst|
        if pst.title.downcase.include?(params[:search_terms].downcase) || pst.body.downcase.include?(params[:search_terms].downcase)
          @posts.push pst
        end
      end
    else
      @posts = Post.order('trending DESC').all
      flash[:notice] = "No posts were found"
      render :index
    end
    
    if @posts == nil || @posts.empty?
      @posts = Post.order('trending DESC').all
      flash[:notice] = "No posts were found"
      render :index
    end
  end
  
  def flagpost
    @post = Post.find(params[:id])
    @post.flagpost=true
    @post.flagcount+=1
    @post.save
     flash[:success] = "post was flagged"
   redirect_to post_path id:@post.id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
       @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, id:"title", :class=>"form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, id:"froala-editor", class:"small_text" %>
  </div>
  <div class="field form-group">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail, id:"thumbnail", :class=>"form-control", :rows=>"10" %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary", id:"submit" %>
  </div>
<% end %>

<%= javascript_tag do %>
  $(function() {
    $('textarea#froala-editor').froalaEditor({
        height: '300'
    })
  });
<% end %>

app/views/posts/_related.html.erb
<div class="media">
  <a href="<%= url_for post_path id: post.id %>">
  <div class="media-left">
      <img class="pull-left img_related" class="media-object" src="<%= image_url post.thumbnail.html_safe %>">
  </div>
  <div class="media-body">
    <strong><%= post.title %></strong>
  </div>
  </a>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if (params.permit(:category_id)).include? :category_id %>
    <h1>Category: <%= Category.find(params.permit(:category_id)[:category_id]).name %></h1>
<% end %>


<div class="row grid">
  <% @posts.each do |post| %>
      <div class="col-sm-6 col-md-3 grid-item">
        <div class="thumbnail">
          <img src="<%= post.thumbnail %>" alt="<%= post.title %>">
          <div class="caption">
            <span class="glyphicon glyphicon-thumbs-up<%= post.is_voted_by_user(@current_user, 0) ? " voted" : "" %>"></span>
            <span><%= post.overall_votes %></span>
            <span class="glyphicon glyphicon-thumbs-down fa-flip-horizontal<%= post.is_voted_by_user(@current_user, 1) ? " voted" : "" %>"></span>
            <span class="glyphicon glyphicon-comment" style="padding-left: 10px; color: cornflowerblue"><%= post.comments.count %></span>
            <h3><%= post.title %></h3>
            <% body = strip_tags(post.body) %>
            <p><%= body[0..200].gsub(/\s\w+\s*$/,'...') %></p>
            <p><a href="<%= url_for post_path(post) %>" class="btn btn-primary" role="button">View</a></p>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/index.html.haml
-#  This file is app/views/posts/index.html.haml
%h1 All Posts

%table#posts
  %thead
    %tr
      %th Forum
  %tbody
    - @posts.each do |pst|
      %tr
        %td= link_to "#{pst.title}", post_path(pst)

= form_tag new_post_path, :method => :get do
  = submit_tag 'Create new post'
  

app/views/posts/new.html.erb
<div class="row">
    <div class="thumbnail">
      <div class="caption">
        <h1>New Post</h1>
        <%= render 'form' %>
      </div>
    </div>
</div>


<%= link_to 'Back', posts_path %>
</div>

app/views/posts/new.html.haml
-#  This file is app/views/posts/new.html.haml
%h1 Create New Post

= form_tag posts_path do

  = label :posts, :title, 'Title'
  = text_field :posts, 'title'

  = label :posts, :text, 'Text'
  = text_field :posts, 'text'

  = submit_tag 'Save Changes'


= link_to 'Return to Posts', posts_path

app/views/posts/search.html.erb
<div class="row grid">
  <% @posts.each do |post| %>
      <div class="col-sm-6 col-md-3 grid-item">
        <div class="thumbnail">
          <img src="<%= post.thumbnail %>" alt="<%= post.title %>">
          <div class="caption">
            <h3><%= post.title %></h3>
            <% body = strip_tags(post.body) %>
            <p><%= body[0..200].gsub(/\s\w+\s*$/,'...') %></p>
            <p><a href="<%= url_for post_path(post) %>" class="btn btn-primary" role="button">View</a></p>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-lg-9" style="padding:12px;background-color:#FEFEFE;line-height:1.4;">
  <p>
    <h2>
      <span id="thumb_upvote" class="glyphicon glyphicon-thumbs-up<%= @current_user ? " cursoronhover" : "" %><%= @post.is_voted_by_user(@current_user, 0) ? " voted" : "" %>"></span>
      <span id="overall_votes"><%= @post.overall_votes %></span>
      <span id="thumb_downvote" class="glyphicon glyphicon-thumbs-down<%= @current_user ? " cursoronhover" : "" %> fa-flip-horizontal<%= @post.is_voted_by_user(@current_user, 1) ? " voted" : "" %>"></span> |
      <strong><%= @post.title %></strong>
    </h2>
  </p>
  
  <p>
    <div style = "background-color:#EEEEEE;">
      <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <%= @post.created_at %>
    </div>
  </p>
  
  <p>
    <%= image_tag(@post.thumbnail.html_safe) %>
  </p>
  
  <p>
    <%= @post.body.gsub("fr-video ", "").html_safe %>
  </p>

  
  <p>
<a href="<%= url_for flagpost_path id: @post.id %>"> <%= submit_tag "flag", :class=>"btn btn-primary" %></a> 
     </p>
  

<div class="fb-share-button" data-href="<%= post_url id:@post.id %>" data-layout="button"></div>

<% if @current_user %>
  <% if  @current_user.id == @post.user_id %><%= link_to 'Edit', edit_post_path(@post) %> | <% end %>
<% end %>
<%= link_to 'Back', posts_path %>

  <% if @current_user %>
      <%
         comment = Comment.new
         comment.post_id = @post.id
      %>
      <%= render partial: "comments/form", locals: {comment: comment} %>
  <% end %>

  <% @post.comments.where(comment_id: nil).each do |comment| %>
  <%= render partial: "comments/show", locals: {comment: comment} %>
  <% end %>



</div>
<div class="col-lg-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Related Posts</h3>
    </div>
    <div class="panel-body">
      <% if @post.related_posts.count == 0 %>
      No related posts.
      <% else %>
        <% @post.related_posts.take(10).each do |post| %>
          <%= render :partial => "related", locals: {post: post} %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>

    function edit_comment(id) {
        $("#body_comment_"+id).hide();
        $("#edit_comment_"+id).show();
        return false;
    }
    function cancel_btn_action(id) {
        $("#body_comment_"+id).show();
        $("#edit_comment_"+id).hide();
        return false;
    }
    function reply_comment(id) {
        $("#post_reply_"+id).show();
        return false;
    }
    function cancel_reply_btn_action(id) {
        $("#post_reply_"+id).hide();
        return false;
    }

    function cast_vote(id, updown) {
////        alert(updown);
//        if ($(id).hasClass("voted")) {
//            alert("You have already casted the vote.");
//        } else {
            $.ajax({
                method: "GET",
                url: "/cast_vote",
                data: { post_id: <%= @post.id %>, updown: updown }
            })
            .done(function( msg ) {
                $("#thumb_upvote").removeClass("voted");
                $("#thumb_downvote").removeClass("voted");
                msg = JSON.parse(msg);
                        if (msg.vote_casted==0) $("#thumb_upvote").addClass("voted");
                        else if (msg.vote_casted==1) $("#thumb_downvote").addClass("voted");
                        $("#overall_votes").text(msg.overall_votes);
            });
//        }
    }


  $(document).ready(function(){
    $("#thumb_upvote").click(function(){cast_vote(this, 0);});
    $("#thumb_downvote").click(function(){cast_vote(this, 1);});
  <% @post.comments.each do |comment| %>
      $("#edit_link_<%= comment.id %>").click(function(){return edit_comment(<%= comment.id %>);});
      $("#cancel_btn_<%= comment.id %>").click(function(){return cancel_btn_action(<%= comment.id %>);});
      $("#reply_link_<%= comment.id %>").click(function(){return reply_comment(<%= comment.id %>);});
      $("#cancel_reply_btn_<%= comment.id %>").click(function(){return cancel_reply_btn_action(<%= comment.id %>);});
  <% end %>
  });
</script>

app/views/posts/show.html.haml
-# in app/views/posts/show.html.haml

%h2 #{@post.title}


%h3 Description:

%p#description= @post.text

= link_to 'Back to posts', posts_path