config/routes.rb
Rails.application.routes.draw do

  
  
  resources :comments
  resources :categories
  resources :posts
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  get '/edit' => 'users#edit'
  get '/signup'  => 'users#new'
  get '/reset_password'  => 'forgot_password#update'
  get '/forgot_password'  => 'forgot_password#new'
  match '/forgot_password' => 'forgot_password#send_email', via: :post
  match '/login', to: 'sessions#create', via: :post
  match '/login', to: 'sessions#new', via: :get
  get '/auth/:provider/callback', :to => 'sessions#create_omniauth'
  get '/auth/failure', :to => 'sessions#failure'
  get '/showprofile' => 'users#show'
 
  
  
  match '/users/validate/:id/:email_confirm_string', to: 'users#validate_from_email', via: :get
  match '/users/pwr/:id/:email_confirm_string', to: 'forgot_password#reset_password', via: :get
  match '/forgot_password.:id', to: 'forgot_password#update', via: :patch
  get '/flagpost', to: 'posts#flagpost'

  get '/logout', :to => 'sessions#destroy'

  get '/login2', :to => 'sessions#create'
  root :to => "posts#index"
  
  get '/search', :to => 'posts#search'

  get '/cast_vote', to: 'votes#cast_vote'
  
   resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <title><%= @post_title.nil? ? "SNN" : @post_title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  
  <body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <div class='modal fade' id="loginModal" tabindex=-1 role="dialog"> 
      <div class='modal-dialog modal-sm'>
        <div class='modal-content'>
          <div class='modal-header'>
            <%= link_to "&times;".html_safe, '#', class: 'close', data:{dismiss:'modal'}, aria:{hidden:'true'} %>
            <h3> Login Form </h3>
          </div>
          <div class='modal-body'>
            <%= link_to "/auth/facebook", {:style=>'color:#3b5998;'} do %>
              <div class="btn-lg btn-block btn-social btn-facebook" background-color="#3b5998"> 
                  <i class="fa fa-facebook"></i> Sign in with Facebook
              </div>
            <% end %>
            <%= form_tag login_path, :method => :post do %>
              <div class='form-group'>
              <%= text_field :user, :email, :class => "form-control", :autocomplete=>"on",:type=>"text", :placeholder=>"Email", :autofocus=>"true", :required=>"true" %>
  	          </div>
              <div class='form-group'>
              <%= text_field :user, :password, :class =>"form-control", :type=>"password",:placeholder=>"Password", :required=>"true" %>
              </div>
              <div class='form-group'>
              <%= submit_tag "Login", :class=>"btn btn-primary" %>
              <a href="<%= url_for '/forgot_password' %>" >Forgot Password</a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= request.base_url %>">SNN</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <div class="navbar-form navbar-left">
            <a class="btn btn-default" href="<%= url_for categories_path %>">
              <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> CATEGORIES
            </a>
          </div>
          <div class="navbar-form navbar-right" role="user-session">
            <% if @current_user.nil? %>
            <!--
            <a class="btn btn-default" href="<%= url_for "/auth/facebook" %>">
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> SIGN IN via Facebook
            </a>
            -->
         
            <a class="btn btn-default" href="#loginModal" data-toggle="modal">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Sign In
            </a>
            <a class="btn btn-default" href= "<%= url_for '/signup' %>">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> SIGN UP
            </a>
            
            <% else %>
            <div class="btn-group">
              <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <%= @current_user.name %>
              </button>
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <a href="<%= url_for user_path id: @current_user.id %>">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> My Profile
                  </a>
                </li>
                 <li>
                  <a href="/edit">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Update Profile 
                  </a>
                </li>
                
                <li>
                  <a href="<%= url_for new_post_path %>">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Create Post
                  </a>
                </li>
                <li>
                  <a href="<%= url_for logout_path %>">
                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Sign Out
                  </a>
                </li>
              </ul>
            </div>
            <% end %>
          </div>
          <form class="navbar-form navbar-right" role="search" action="search">
            <div class="input-group">
              <input type="text" class="form-control" name="search_terms" placeholder="Search">
              <span class="input-group-btn">
                <button class="btn btn-default" name="submit_search" type="submit">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Social News Network</p>
      </footer>

    </div> <!-- /container -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.2.0/imagesloaded.pkgd.min.js"></script>

    <script>
        $(".grid").imagesLoaded(function() {
            $('.grid').masonry({
                itemSelector: '.grid-item'
            });
        });
    </script>

  </body>
</html>